### ISSUE TITLE
[BUG] K2GX skin HF button background color missing at times

### ISSUE THREAD

**Issue by K7MDL2** [mi0bot/OpenHPSDR-Thetis#103]
On startup with the K2GX World Blue-RGB skin, or when switching to the K2GX World Blue-RGB - while on a XVTR band the HF button is missing the background (appears translucent white) until you change to the HF band range.  Then switching back to VHF+ range buttons all works though the HF has a green background unlike other skins which have black backgrounds.

I suspect the Skin should load a black background for all cases.

![{F070C972-F845-4DEB-8287-1C38877076DC}](https://github.com/user-attachments/assets/04b0ec42-c92c-4087-9651-95edc6f1a449)

![{DA71DF18-367C-444F-9F57-1E568D473E49}](https://github.com/user-attachments/assets/bdd609a2-a8b5-4595-a038-8bc2efbab045)

![{07A20EF9-771F-4C14-9DE3-22A254196E4B}](https://github.com/user-attachments/assets/517a3e0c-b3c3-47c0-92e5-1e2d7bbe96e3)

**Desktop (please complete the following information):**
Win11 Pro, NUC 12 with Core i7, 32GB ram, 1TB SSD. 
Thetis version is v2.20.3.7 x64 for HL2 Beta 1

**Comment by DH1KLM** [comment]
Not a bug in Thetis I assume.
I would try do download the skin via the Skin Server Tab and navigate to W1AEX's server again.
I Could not notice a missing background.

![image](https://github.com/user-attachments/assets/a94e7777-699a-4ce1-b8ef-b3e1703511cc)

**Comment by K7MDL2** [comment]
It appears unique to K2GX World Blue-RGB and World Green-RGB. The K2GX World Time-RGB works correctly.   

I went to the servers tab as suggested.  You can download the skin of choice and see the HF button color issue immediately with the 2 filenames mentioned.

**Comment by DH1KLM** [comment]
Ok got it. Go to your skin folder and search for btnBandHF-0.png.png. Remove the duplicate .png extension.

**Comment by K7MDL2** [comment]
Good catch, hat fixed it.  That was a funny looking file name.

**Comment by K7MDL2** [comment]
I contacted W1AEX and he has fixed the posted sources.
