### ISSUE TITLE
[FEATURE] Pull skins from GitHub directly ?

### ISSUE THREAD

**Issue by Aleziss** [mi0bot/OpenHPSDR-Thetis#32]
**Is your feature request related to a problem? Please describe.**
No. But would there be a way to pull skins directly from GitHub from the Skin Server list ?

That way, where there are changes, updates could be pushed to GitHub and updated automatically when user redownload the skin by overring previous files. 

**Describe the solution you'd like**
I did create a skin that I host on GitHub. I had my skin based on Thetis v2.10.0-HL2 by MI0BOT. 

Now with the latest Thetis v2.10.3.4, button size have changed and placement have also changed on some graphical items.

I did upgrade my skin to match the latest version of Thetis but the person that host my file has to verify when I do some changes. If he does not follow my GitHub, the skin will never be updated from within Thetis skin server.

**Describe alternatives you've considered**
I don't know how this could be done otherwhise, I think GitHub is a nice platform to host files and push changes. That way we do not rely on other users servers to host our files.

It would also be mice to have a solution to reflect revisions and skins versions that are tied to various Thetis version as changes can be made at any time in graphics size and positions. 

**Additional context**
Hopefully that would be possible to host skins from GitHub servers.

[My GitHub Skin](https://github.com/Aleziss/OpenHPSDR-Thetis-Skins)

Thanks for the awesome work you guys are all doing on Thetis and the HL2 support.

**Comment by ramdor** [comment]
I am yet to write a document/video explaining how host the skin json files, and get your hosted json file added to the master skin server list. Obviously there has to be some level of control to this otherwise we could end up with a pile of unsuitable skins available. I might have some time to write the doc/video later/tomorrow.

**Comment by Aleziss** [comment]
> I am yet to write a document/video explaining how host the skin json files, and get your hosted json file added to the master skin server list. Obviously there has to be some level of control to this otherwise we could end up with a pile of unsuitable skins available. I might have some time to write the doc/video later/tomorrow.
> 
> edit: a chap has emailed me direct about this as well, which I still havent had a chance to reply to.

Awesome, that would be really nice that it also works from GitHub.

I thought about that also that there might be TONS of skins coming from everywhere and not always built the right way.

I took a long time to figure out the proper size panels and scale my high quality buttons so everything fits nicely.

I can't wait to get things sorted out and hopefully I will be able to share my work correctly and follow the updates accordingly which is currently not happening since my files are hosted to another OM server.

Thanks so much for getting back to my suggestion !

**Comment by ramdor** [comment]
Ah, i forgot about this @Aleziss .  If you take a look at https://github.com/ramdor/ThetisSkins  that repo is setup to contain the default skins, and Thetis uses that repo directly.  When I get some time I will add a readme over there to explain what is going on, but you might be able to find enough info out just by looking at the json.  If you look in the main Thetis repo at the [skin_servers.json](https://github.com/ramdor/Thetis/blob/master/skin_servers.json) you can see that it points back to the ThetisSkins repo json.

**Comment by Aleziss** [comment]
Thanks Richie, I will examinate your links and also be on the lookout for the readme file.
