### ISSUE TITLE
errore 

### ISSUE THREAD

**Issue by iw8rvq** [mi0bot/OpenHPSDR-Thetis#50]
[v2.10.3.5-beta1](https://github.com/mi0bot/OpenHPSDR-Thetis/releases/tag/v2.10.3.5-beta1) questa non funziona per niente non parte il software ci sono errori.

**Comment by DH1KLM** [comment]
Start Thetis with CTRL Key pressed.  And please write in english.

**Comment by iw8rvq** [comment]
Thank you. now works

Il 03.03.2024 22:07 Sigi ha scritto: 

> Start
Thetis with CTRL Key pressed. And please write in english. 
> 
> --
>
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].
> You are receiving this because you authored the thread.Message
ID: @github.com>
