### ISSUE TITLE
[BUG] Fatal Error

### ISSUE THREAD

**Issue by Aleziss** [mi0bot/OpenHPSDR-Thetis#52]
**Describe the bug**
Uninstalled previous Ramdor v2.10.3.4 and then intalled Ramdor Thetis v2.10.3.5.

I then copied v2.10.3.5-HL2β2 on a different folder and as soon I try to open it, I get a `Fatal Error` message box.

Ramdor v2.10.3.5 does start correctly and seem to be working well.

**To Reproduce**
I simply try to start v2.10.3.5-HL2β2 and this `Fatal Error` occurs `Index was outside the bounds of the array.`

When I hit `OK`, v2.10.3.5-HL2β2 closes.

**Expected behaviour**
Just start.

**Screenshots**

![image](https://github.com/mi0bot/OpenHPSDR-Thetis/assets/57082992/c13fbbcb-393c-4bd6-909e-7947dbccfaaa)

**Desktop (please complete the following information):**
 - OS: Windows10

**Additional context**
2.10.3.4 worked well, now this issue with HL2beta2

I uninstalled EVERYTHING with RevoUninstaller, deleted v2.10.3.5-HL2β2 folder and anythying related to Thetis in the registry, restarted the computer and redo the install and copy of v2.10.3.5-HL2β2 and still the same issue.

v2.10.3.5-HL2β1 same `Fatal Error` occurs.

Thank you.

**Comment by Aleziss** [comment]
I think I found the issue, I deleted `C:\Users\MyPC\AppData\Roaming\OpenHPSDR\Thetis-HL2-x64` folder and now it's doing the Planning calculations.. I think after it will finally start. I'll report here when it is able to properly start.

**Comment by Aleziss** [comment]
Yes that was the issue, after calculations, v2.10.3.5-HL2β1 and v2.10.3.5-HL2β2 starter properly. I just need to redo my database.

Thanks.

**Comment by DH1KLM** [comment]
All you had to do was hold down the CTRL key when starting Thetis.
This "bug" was already present in Beta1 and was addressed in the HL2 Facebook group.

![image](https://github.com/mi0bot/OpenHPSDR-Thetis/assets/27503182/5911ea84-7d60-42ca-81d3-c7c8d3fad216)
