### ISSUE TITLE
problem upgrading

### ISSUE THREAD

**Issue by irlrocket** [mi0bot/OpenHPSDR-Thetis#56]
I am upgrading to v2.10.3.5-beta2 from v2.10.3.3
I uninstalled the ramdor version and installed v2.10.3.5, which runs ok
I then extract the new mi0bot v2.10.3.5-beta2 
when i try running - i get an index out of bounds error

![image](https://github.com/mi0bot/OpenHPSDR-Thetis/assets/29229320/1debd7f0-3dc5-4616-8ee8-790f98b297c7)

i have tried resetting the database in the ramdor version -but that has not helped
Can you advise?

**Comment by Aleziss** [comment]
Answer in this [close post](https://github.com/mi0bot/OpenHPSDR-Thetis/issues/52#issuecomment-2014892206), you should be good to go.

**Comment by irlrocket** [comment]
Thanks Aleziss - much appreciated
