### ISSUE TITLE
Blank windows - Setup/Spotting

### ISSUE THREAD

**Issue by la5zo** [mi0bot/OpenHPSDR-Thetis#92]
I am unable to open the Setup screen. Nothing happens when I click Setup (2nd time).
Using Alt-TAB I can see a blank window labeled setup - but when I try to open it - it blanks out any other window on the same screen.

My setup is 3 displays setup as extended workspace.  OS is Windows 10 Home on an i7. 
This started after updating to latest Thetis version 2.10.3.6
The same thing goes for Spotting.  Diversity won't start either - and it dosn't show up when using Alt-TAB.

However, installed ver. 2.10.3.6 on a LapTop running Windows 11 Home and all was fine there ?!  Confused....
What is wrong, any suggestion for a fix ?

Geir/LA5ZO

Latest:
Got it working when going back to an older database.  16.10.2024  Geir

**Comment by ramdor** [comment]
It is most likely that the forms are displayed off screen as this area of code needs to be reworked. It will only work at the moment if your screens form a rectangle. Using different resolution screens can cause this issue.  Turn off all but one monitor, start thetis and forms should return to that monitor, shut down thetis, turn other monitors on, restart Thetis and it should recover.

When I get the time/interest I will rework the ForceOnScreen code to work with irregular monitor layouts.
